# -*- coding: utf-8 -*-
"""pmnl pro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IUGUQLHy9Nsn0_YAj_WYznN8E7NuCgAc
"""



import requests
import copy
import math

# =============================
# CONFIG
# =============================
BASE_URL = "https://api.pmnlpro.pk"
EMAIL = "sahirstudio1177@gmail.com"
PASSWORD = "Sahir_4476773"

PER_PAGE = 50        # products per page
UPDATE_ACTIVE = True # True = real update, False = dry run

# =============================
# WHAT YOU WANT TO CHANGE (GLOBAL)
# =============================
EDIT_DATA = {
    # leave None if you don't want to change
    "active": True,
    # example:
    # "commission": 800,
}

# =============================
# SESSION
# =============================
session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0",
    "Accept": "application/json"
})

# =============================
# LOGIN
# =============================
login = session.post(
    f"{BASE_URL}/api/auth/login",
    data={"email": EMAIL, "password": PASSWORD}
)

print("Login:", login.status_code)
if login.status_code != 200:
    raise Exception("Login failed")

# =============================
# GET FIRST PAGE (to know total pages)
# =============================
first = session.get(
    f"{BASE_URL}/api/products?page=1&limit={PER_PAGE}&status=true"
).json()

total = first["total"]
pages = first["pages"]

print(f"Total products: {total}")
print(f"Total pages: {pages}")

updated_count = 0

# =============================
# LOOP THROUGH PAGES
# =============================
for page in range(1, pages + 1):
    print(f"\n--- Page {page}/{pages} ---")

    res = session.get(
        f"{BASE_URL}/api/products?page={page}&limit={PER_PAGE}&status=true"
    ).json()

    for product in res["docs"]:
        payload = copy.deepcopy(product)

        # -----------------------------
        # APPLY CHANGES (SAFE)
        # -----------------------------
        for key, value in EDIT_DATA.items():
            if value is not None:
                payload[key] = value

        # remove read-only fields
        for k in ["createdAt", "updatedAt", "__v", "dateCreated"]:
            payload.pop(k, None)

        if not UPDATE_ACTIVE:
            print(f"[DRY RUN] Product {payload['product_no']}")
            continue

        update = session.put(
            f"{BASE_URL}/api/products",
            json=payload
        )

        if update.status_code == 200:
            updated_count += 1
            print(f"✔ Updated product_no {payload['product_no']}")
        else:
            print(f"❌ Failed product_no {payload['product_no']}")
            print(update.text)

print(f"\n✅ DONE. Total updated: {updated_count}")